# basics
model = "apqgan"
dataset = "fashion_mnist"

# training
training_optimizer = "adam"
learning_rate = 1e-2
max_epochs = 8
batch_size = 16
seed = 100

# torch lightning
task = "image_generation"
num_workers = 0
num_devices = 1
accelerator = "cpu"
project = 'test_tl/fashion_mnist/seed100'

# metrics configuration
[metrics]
use_metrics = ['NDB_JSD_EvaluationCallback', 'FIDEvaluationCallback', 'GANImagesCallback']

# Define initialization parameters for each metric

[metrics.NDB_JSD_EvaluationCallback]
every_n_epochs = 1
number_of_bins=50
significance_level=0.05
z_threshold= 4
whitening=false
max_dims= "NA"

[metric.FIDEvaluationCallback]
every_n_epochs = 1
feature = 64
reset_real_features = false
normalize = true
