# basics
model = "qgan_probs"
dataset = "mnist"

# training
training_optimizer = "adam"
learning_rate = 1e-2
max_epochs = 10
batch_size = 25
num_qubits = 10
n_samples = 500

# torch lightning
task = "image_generation"
num_workers = 0
num_devices = 1
accelerator = "cpu"
project = "qgan_probs"
log_every_n_steps=1


# metrics configuration
[metrics]
use_metrics = ['GANImagesCallback']