# basics
model = "qinr"
dataset = "mnist"
seed = 42

# training
training_optimizer = "adam"
learning_rate = 1e-2
max_epochs = 20
batch_size = 8
n_samples = 2400

# torch lightning
task = "image_generation"
num_workers = 0
num_devices = 1
accelerator = "cpu"
project = 'qinr_test4'

# metrics configuration
[metrics]
use_metrics = ['TSNEPlotCallback', 'FID', 'GANImagesCallback', 'NDB_JSD']

[metrics.FIDEvaluationCallback]
every_n_epochs = 1

[metrics.TSNEPlotCallback]
every_n_epochs = 1

[metrics.NDB_JSD_EvaluationCallback]
every_n_epochs = 1
number_of_bins=50
significance_level=0.05
z_threshold= "NA"
whitening=false
max_dims= "NA"