# basics
model = "su2"
dataset = "2d_gaussian"
transform = "minmax"
# training
training_optimizer = "adam"
learning_rate = 0.1
max_epochs = 100
batch_size = 1
n_qubits = 8

# torch lightning
task = "probs_generation"
num_workers = 0
num_devices = 1
accelerator = "cpu"
project = "su2"
log_every_n_steps=1
# load
#load_name = "../qumet_output/qgcd_probs_generation_2d_gaussian_2024-02-29/software/training_ckpts/last.ckpt"
#load_type = "pl"