# basics
model = "efficientsu2"
dataset = "2d_ring_gaussian_b"

# training
training_optimizer = "adam"
learning_rate = 1e-2
max_epochs = 20
batch_size = 256
num_qubits = 10

# torch lightning
task = "bitstring_generation"
num_workers = 0
num_devices = 1
accelerator = "cpu"
project = "efficientsu2/discrete/2d_ring_gauss_0.05/10qubit/"
# load
#load_name = "../qumet_output/qgcd_probs_generation_2d_gaussian_2024-02-29/software/training_ckpts/last.ckpt"
#load_type = "pl"