# basics
model = "qcbm"
dataset = "bars_and_stripes"

# training
n_qubits = 9
training_optimizer = "adam"
learning_rate = 1e-1
max_epochs = 50
batch_size = 512

# torch lightning
task = "probs_generation"
num_workers = 0
num_devices = 1
accelerator = "cpu"

project = "bars_and_stripes"