# basics
model = "pqwgan_qc"
add_vae = true

dataset = "mnist"
seed = 1

# training
training_optimizer = "adam"
learning_rate = 1e-2
max_epochs = 8
batch_size = 8
n_samples = 2400

# torch lightning
task = "image_generation"
num_workers = 0
num_devices = 1
accelerator = "cpu"
project = 'vae_qwgan/mnist/seed1'

# metrics configuration
[metrics]
use_metrics = ['TSNEPlotCallback', 'FID', 'NDB_JSD']

# Define initialization parameters for each metric

[metrics.NDB_JSD_EvaluationCallback]
every_n_epochs = 1
number_of_bins=50
significance_level=0.05
z_threshold= "NA"
whitening=false
max_dims= "NA"

[metrics.FIDEvaluationCallback]
every_n_epochs = 1

[metrics.TSNEPlotCallback]
every_n_epochs = 1

